stages:
  - build

variables:
  REPOSITORY_PREFIX: harbor.mock.org/cloudnative/horizon/

before_script:
  - export APP_REVISION="${CI_COMMIT_TAG:-${CI_COMMIT_REF_NAME##*/}-r$CI_PIPELINE_ID}"
  - export CHART_VERSION="${CI_COMMIT_TAG:-v0.0.0-r$CI_PIPELINE_ID}"

build:
  stage: build
  variables:
    DOCKER_CONFIG_JSON: $DOCKER_AUTH_CONFIG_DEV
  script:
    - bash build/build.sh || exit 1
  only:
    - develop
    - tags
  except:
    - schedules
