stages:
  - lint
  - unit-test
  - build

variables:
  COVERAGE_STANDARD: 70
  REPOSITORY_PREFIX: harbor.mock.org/cloudnative/horizon/
  GOPROXY: https://goproxycn,direct

golint:
  stage: lint
  script:
    - golangci-lint run
  only:
    refs:
      - merge_requests
    variables:
      - $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "develop"

unit-tests:
  stage: unit-test
  script:
    - |
      COVERAGE=$(. .unit-test.sh)
      [[ "$?" == 0 ]] || exit 1
      [[ $(awk -v M=$COVERAGE -v N=$COVERAGE_STANDARD 'BEGIN{print(M>=N)?"0":"1"}') == "0" ]] && \
      echo "coverage is $COVERAGE" || {
        echo "coverage is $COVERAGE, is less than $COVERAGE_STANDARD"; exit 1
      }
  only:
    refs:
      - merge_requests
    variables:
      - $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "develop"
      - $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"

build:
  stage: build
  variables:
    DOCKER_CONFIG_JSON: $DOCKER_AUTH_CONFIG_ONLINE
  script:
    - bash build/build.sh || exit 1
  only:
    - develop
    - tags
  except:
    - schedules
