# "horizon:O{AyroRA@@tcp(music-horizon-dev-jd-26519.rds.cn-east-p1.internal:3331)/horizon?charset=utf8mb4&parseTime=True&loc=Local"
serverConfig:
  port: 8181
cloudEventServerConfig:
  port: 8282
dbConfig:
  host: music-horizon-dev-jd-26519.rds.cn-east-p1.internal
  port: 3331
  username: horizon
  password: O{AyroRA@
  database: horizon
  prometheusEnabled: true
oidcConfig:
  userHeader: X-HORIZON-OIDC-USER
  fullNameHeader: X-HORIZON-OIDC-FULLNAME
  emailHeader: X-HORIZON-OIDC-EMAIL
  oidcIDHeader: X-HORIZON-OIDC-ID
  oidcTypeHeader: X-HORIZON-OIDC-TYPE
gitlabMapper:
  control:
    httpURL: https://g.hz.netease.com
    # token for grp.cloudnative
    token: ""
  compute:
    httpURL: http://cicd.mockserver.org
    sshURL: ssh://git@music-cicd-gitlab-test.hz.netease.com:22222
    token: ""
gitlabRepoConfig:
  application:
    parent:
      path: music-cloud-native/applications
      id: 4278
    recyclingParent:
      path: music-cloud-native/recycling-applications
      id: 4586
  cluster:
    parent:
      path: music-cloud-native/clusters
      id: 4279
    recyclingParent:
      path: music-cloud-native/recycling-clusters
      id: 4587
helmRepoMapper:
  dev,test,reg,perf,beta,pre,online: "https://harbor.mock.org/chartrepo/horizon-template"
argoCDMapper:
  dev,test,reg,perf,beta,pre,online:
    url: http://argocd.yf-dev2.netease.com
    token: ""
tektonMapper:
  dev,test,reg,perf,beta,pre,online:
    server: http://el-horizon-listener.tekton-resources:8080
    namespace: tekton-resources
    # if you run horizon on local machine, you need to set this to the absolute path of your kubeconfig
    # if you are running it on mac, the path may be looked like '/Users/xxx/.kube/config'
    kubeconfig: /Users/tomsun/.kube/config
    s3:
      accessKey: 
      secretKey: 
      region: us-east-1
      endpoint: nos-jd.service.163.org
      bucket: yufeng-collector-dev
      skipVerify: true
      s3ForcePathStyle: true
grafanaMapper:
  hz-dev2:
    basicDashboard: "http://grafana.yf-dev2.netease.com/d/R3l8AsF7z/pod-resources?orgId=1&kiosk&theme=light&var-namespace=%s&var-datasource=Prometheus&var-cluster=%s"
    serverlessDashboard: "http://grafana.yf-dev2.netease.com/d/mkwWamKnk/knative-user?orgId=1&kiosk&theme=light&var-datasource=Prometheus&var-cluster=%s"
    querySeries: "http://grafana.yf-dev2.netease.com/api/datasources/proxy/1/api/v1/series"
grafanaSLO:
    overviewDashboard: "http://grafana.yf-dev2.netease.com/d/Wz3GSBank/slo-gai-lan?orgId=1&kiosk&theme=light&var-env=%s"
    apiDashboard: "http://grafana.yf-dev2.netease.com/d/tKjaD1-nk/horizon-api-slo?orgId=1&kiosk&theme=light"
    pipelineDashboard: "http://grafana.yf-dev2.netease.com/d/g40XAtbnk/horizon-pipeline-slo?orgId=1&kiosk&theme=light&var-env=%s"

oauthHTMLLocation: /Users/tomsun/Workspace/cloudmusic/code/horizon/horizon/core/http/api/v1/oauthserver/auth.html

