# "horizon:O{AyroRA@@tcp(music-horizon-dev-jd-26519.rds.cn-east-p1.internal:3331)/horizon?charset=utf8mb4&parseTime=True&loc=Local"
serverConfig:
  port: 8080
cloudEventServerConfig:
  port: 8181
dbConfig:
  host: music-horizon-dev-jd-26519.rds.cn-east-p1.internal
  port: 3331
  username: horizon
  password: O{AyroRA@
  database: horizon
  prometheusEnabled: true
sessionConfig:
  maxAge: 43200
redisConfig:
  protocol: tcp
  address: dev.redis:6379
  password: redis
  db: 1
oidcConfig:
  userHeader: X-HORIZON-OIDC-USER
  fullNameHeader: X-HORIZON-OIDC-FULLNAME
  emailHeader: X-HORIZON-OIDC-EMAIL
  oidcIDHeader: X-HORIZON-OIDC-ID
  oidcTypeHeader: X-HORIZON-OIDC-TYPE
gitlabMapper:
  template:
    httpURL: https://g.hz.netease.com
    # token for grp.cloudnative
    token: ""
  code:
    httpURL: https://g.hz.netease.com
    # token for grp.cloudnative
    token: ""
  gitops:
    httpURL: http://cicd.mockserver.org
    sshURL: ssh://git@music-cicd-gitlab-test.hz.netease.com:22222
    token: ""
gitopsRepoConfig:
  rootGroupPath: music-cloud-native
templateRepo:
  host: "https://harbor.mock.org"
  repoName: "horizon-template"
  username: ""
  password: ""
  insecure: true
  certFile: ""
  keyFile: ""
  caFile: ""
argoCDMapper:
  dev,test,reg,perf,beta,pre,online:
    url: http://argocd.yf-dev2.netease.com
    token: ""
tektonMapper:
  dev,test,reg,perf,beta,pre,online:
    server: http://el-horizon-listener.tekton-resources:8080
    namespace: tekton-resources
    # if you run horizon on local machine, you need to set this to the absolute path of your kubeconfig
    # if you are running it on mac, the path may be looked like '/Users/xxx/.kube/config'
    kubeconfig: "/Users/wurongjun/.kube/config"
    s3:
      accessKey: 
      secretKey: 
      region: us-east-1
      endpoint: nos-jd.service.163.org
      bucket: yufeng-collector-dev
      disableSSL: false
      skipVerify: true
      s3ForcePathStyle: true
grafanaSLO:
  overviewDashboard: "http://grafana.yf-dev2.netease.com/d/Wz3GSBank/slo-gai-lan?orgId=1&kiosk&theme=light&var-env=%s"
  apiDashboard: "http://grafana.yf-dev2.netease.com/d/tKjaD1-nk/horizon-api-slo?orgId=1&kiosk&theme=light"
  pipelineDashboard: "http://grafana.yf-dev2.netease.com/d/g40XAtbnk/horizon-pipeline-slo?orgId=1&kiosk&theme=light&var-env=%s"
grafanaConfig:
  host: http://localhost:3000
  namespace: horizon
  dashboards:
    # label that the configmaps with dashboards are marked with
    labelKey: grafana_dashboard
    # value of label that the configmaps with dashboards are set to
    labelValue: "1"
  syncDatasourceConfig:
    period: 2m
    # label that the configmaps with datasources are marked with
    labelKey: grafana_datasource
    # value of label that the configmaps with datasources are set to
    labelValue: "1"
oauth:
  # if you run horizon on local machine, you need to set this to the absolute path of your auth.html
  # for example ${projectdir}/core/http/api/v1/oauthserver/auth.html
  oauthHTMLLocation:
  authorizeCodeExpireIn: 10m
  accessTokenExpireIn: 24h

