openapi: 3.0.1
info:
  title: Horizon Application API
  description: |
    This API
  version: 1.0.0
tags:
  - name: application
paths: {}
components:
  schemas:
    application:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string