openapi: 3.0.1
info:
  title: Horizon-core
  version: 1.0.0
servers:
  - url: 'http://horizon.mockserver.org/'
paths: {}

components:
  parameters:
    pageIndex:
      name: pageIndex
      in: path
    pageSize:
      name: pageSize
      in: path

  schemas:
    PageParams:
      type: object
      properties:
        current:
          type: number
        pageSize:
          type: number

    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string