openapi: 3.0.1
info:
  title: Horizon-core
  version: 1.0.0
servers:
  - url: 'http://horizon.mockserver.org/'
paths:
  /api/v1/resources?path={path}:
    get:
      summary: get resource type and id by path
      operationId: getResource
      parameters:
        - name: path
          in: query
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                properties:
                  resourceType:
                    $ref: "#/components/schemas/resourceType"
                  resourceId:
                    type: integer
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

components:
  parameters:
    pageNumber:
      name: pageNumber
      in: query
    pageSize:
      name: pageSize
      in: query

  schemas:
    PageParams:
      type: object
      properties:
        current:
          type: number
        pageSize:
          type: number

    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: string
        message:
          type: string
        requestId:
          type: string

    resourceType:
      type: string
      enum:
        - group
        - application
        - applicationInstance

    Date:
      type: string
      format: date
      pattern: full-date