openapi: 3.0.1
info:
  title: Horizon Group API
  description: |
    This API
  version: 1.0.0
tags:
  - name: service
paths:
  /services:
    get:
      operationId: getService
      summary: delete an empty group
      responses:
        '200':
          description: null response

components:
  schemas:
    serviceDetail:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string