openapi: 3.0.1
info:
  title: Horizon Application Front
  version: 1.0.0
servers:
  - url: 'http://localhost:8080/'
paths:
  /apis/front/v1/applications/searchapplications?filter={filter}&pageNumber=${pageNumber}&pageSize={pageSize}:
    get:
      tags:
        - application
      description: search applications by name fuzzily
      operationId: searchApplications
      parameters:
        - name: filter
          in: query
          description: "part of name for fuzzy matching"
        - $ref: 'common.yaml#/components/parameters/pageNumber'
        - $ref: 'common.yaml#/components/parameters/pageSize'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/listApplicationsResp'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "common.yaml#/components/schemas/Error"

  /apis/front/v1/applications/searchmyapplications?filter={filter}&pageNumber=${pageNumber}&pageSize={pageSize}:
    get:
      tags:
        - application
      description: search my applications by name fuzzily
      operationId: searchMyApplications
      parameters:
        - name: filter
          in: query
          description: "part of name for fuzzy matching"
        - $ref: 'common.yaml#/components/parameters/pageNumber'
        - $ref: 'common.yaml#/components/parameters/pageSize'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/listApplicationsResp'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "common.yaml#/components/schemas/Error"
components:
  schemas:
    listApplicationsResp:
      type: object
      properties:
        total:
          type: integer
        items:
          type: array
          items:
            $ref: '#/components/schemas/application'
    application:
      type: object
      properties:
        id:
          $ref: '#/components/schemas/id'
        groupID:
          $ref: '#/components/schemas/groupID'
        name:
          $ref: '#/components/schemas/name'
        fullName:
          $ref: '#/components/schemas/fullName'
        fullPath:
          $ref: '#/components/schemas/fullPath'
        createdAt:
          $ref: '#/components/schemas/createdAt'
        updatedAt:
          $ref: '#/components/schemas/updatedAt'
    id:
      type: integer
      format: int64
      description: id of application
    groupID:
      type: integer
      format: int64
      description: id of group
    createdAt:
      type: string
      description: creation time of application, contains the timezone
    updatedAt:
      type: string
      description: creation time of application, contains the timezone
    name:
      type: string
      description: name of application
    fullName:
      type: string
      description: full name of application
    fullPath:
      type: string
      description: full path of application