openapi: 3.0.1
info:
  title: Horizon-Terminal-Front
  description: Front API About Terminal
  version: 1.0.0
servers:
  - url: 'http://localhost:8080/'
paths:
  /apis/front/v1/terminal/{terminalID}/websocket:
    parameters:
      - name: terminalID
        in: path
        description: id of terminal session
        required: true
    get:
      tags:
        - terminal
      operationId: connectTerminal
      summary: connect to terminal
      responses:
        '200':
          description: Succuss
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "common.yaml#/components/schemas/Error"