openapi: 3.0.1
info:
  title: Horizon-Pipelinerun-Restful
  version: 2.0.0
servers:
  - url: 'http://localhost:8080/'
paths:
  /apis/core/v2/pipelineruns/{pipelinerunID}/stop:
    parameters:
      - $ref: 'common.yaml#/components/parameters/paramPipelinerunID'
    post:
      tags:
        - pipelinerun
      operationId: stopPipelinerun
      summary: |
        Stop the running pipelinerun for a cluster.
        If there is no running pipelinerun, do nothing and return success.
        A cluster can only have one running pipelinerun.
      responses:
        "200":
          description: Success
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "common.yaml#/components/schemas/Error"

  /apis/core/v2/pipelineruns/{pipelinerunID}/log:
    parameters:
      - $ref: 'common.yaml#/components/parameters/paramPipelinerunID'
    get:
      tags:
        - pipelinerun
      operationId: getPipelineRunLog
      summary: |
        Get the specified pipelinerun's log for a cluster.
      responses:
        "200":
          description: Success
          content:
            text/plain:
              schema:
                example: |
                  xxxxxxxxxxxx
                  xxxxxxxxxxxx
                  xxxxxxxxxxxx
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "common.yaml#/components/schemas/Error"

  /apis/core/v2/pipelineruns/{pipelinerunID}:
    parameters:
      - $ref: 'common.yaml#/components/parameters/paramPipelinerunID'
    get:
      tags:
        - pipelinerun
      operationId: getPipelinerun
      summary: |
        Get the specified pipelinerun.
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetPipelineRunResp"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "common.yaml#/components/schemas/Error"

  /apis/core/v2/pipelineruns/{pipelinerunID}/diffs:
    parameters:
      - $ref: 'common.yaml#/components/parameters/paramPipelinerunID'
    get:
      tags:
        - pipelinerun
      operationId: getPipelineRunDiff
      summary: |
        Get the specified pipelinerun's diff
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PipelineRunDiff"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "common.yaml#/components/schemas/Error"

  /apis/core/v2/clusters/:%v/pipelineruns:
    parameters:
      - $ref: 'common.yaml#/components/parameters/paramClusterID'
      - $ref: 'common.yaml#/components/parameters/pageNumber'
      - $ref: 'common.yaml#/components/parameters/pageSize'
      - name: canRollback
        in: query
        schema:
          type: boolean
        description: whether the pipelinerun can rollback
    get:
      tags:
        - pipelinerun
      operationId: getClusterPipelineRuns
      summary: |
        Get pipelineruns of a cluster.
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    properties:
                      total:
                        type: integer
                      items:
                        type: array
                        items:
                          $ref: "#/components/schemas/PipelineRun"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "common.yaml#/components/schemas/Error"

components:
  schemas:
    PipelineRun:
      type: object
      properties:
        action:
          type: string
          description: "action of pipelinerun"
          enum: ["builddeploy", "deploy", "restart", "rollback"]
        canRollback:
          type: boolean
          description: "whether this pipelinerun can be specified to rollback"
        configCommit:
          type: string
          description: "commit of config repository"
        createdAt:
          type: string
        createdBy:
          $ref: "common.yaml#/components/schemas/User"
        description:
          type: string
        finishedAt:
          type: string
        gitBranch:
          type: string
          description: branch of source code
        gitCommit:
          type: string
          description: commit of source code
        gitURL:
          type: string
          description: url of source code
        id:
          type: integer
        imageURL:
          type: string
          description: full url of image
        lastConfigCommit:
          type: string
          description: "last commit of config repository"
        startedAt:
          type: string
          description: "start time of pipelinerun"
        status:
          type: string
          enum: ["ok", "waiting", "failed", "canceled"]
        title:
          type: string
          description: "title of pipelinerun"
        updatedAt:
          type: string
          description: "update time of pipelinerun"
    GetPipelineRunResp:
      type: object
      properties:
        data:
          $ref: "#/components/schemas/PipelineRun"
    PipelineRunDiff:
      type: object
      properties:
        data:
          type: object
          properties:
            codeInfo:
              type: object
              properties:
                branch:
                  type: string
                  description: "branch of source code"
                commitID:
                  type: string
                  description: "latest commit id of source code"
                commitMsg:
                  type: string
                  description: "lastest commit message of source code"
                link:
                  type: string
                  description: "link of lastest commit"
            codeDiff:
              type: object
              properties:
                diff:
                  type: string
                  description: "changed content of this pipelinerun"
                from:
                  type: string
                  description: "the last commit before the change"
                to:
                  type: string
                  description: "the last commit after the change"