openapi: 3.0.3
info:
  title: Horizon-Cluster-Restful-V2
  description: Title
  version: 1.0.0
servers:
  - url: 'http://localhost:8080/'
paths:
  /apis/core/v2/applications/{applicationNameID}/clusters:
    parameters:
      - name: applicationNameID
        in: path
        description: application id
        schema:
          type: string
        required: true
    post:
      tags:
        - cluster
      operationId: createCluster
      summary: Create a cluster
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateCluster'
      responses:
        "200":
          description: Success
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "common.yaml#/components/schemas/Error"

  /apis/core/v2/clusters/{clusterNameID}:
    parameters:
      - name: clusterNameID
        in: path
        description: cluster name or cluster id
        schema:
          type: string
        required: true
    get:
      tags:
        - cluster
      operationId: getCluster
      summary: get a cluster
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetClusterResponse"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "common.yaml#/components/schemas/Error"

    put:
      tags:
        - cluster
      operationId: updateCluster
      summary: update a cluster
      responses:
        "200":
          description: Success
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "common.yaml#/components/schemas/Error"
components:
  schemas:
    CreateCluster:
      type: object
      required:
        - name
        - description
      properties:
        name:
          $ref: '#/components/schemas/Name'
        description:
          $ref: '#/components/schemas/Description'
        git:
          oneOf:
            - $ref: '#/components/schemas/GitBranch'
            - $ref: '#/components/schemas/GitCommit'
            - $ref: '#/components/schemas/GitTag'
        tags:
          type: array
          items:
            $ref: '#/components/schemas/Tag'
        buildConfig:
          $ref: '#/components/schemas/buildConfig'
        templateInfo:
          $ref: '#/components/schemas/TemplateInfo'
        templateConfig:
          $ref: '#/components/schemas/TemplateConfig'

    GetClusterResponse:
      type: object
      properties:
        id:
          $ref: "common.yaml#/components/schemas/ID"
        name:
          $ref: '#/components/schemas/Name'
        description:
          $ref: '#/components/schemas/Description'
        priority:
          $ref: '#/components/schemas/Priority'
        scope:
          $ref: '#/components/schemas/Scope'
        fullPath:
          type: string
        applicationName:
          $ref: '#/components/schemas/Name'
        applicationID:
          $ref: "common.yaml#/components/schemas/ID"
        tags:
          type: array
          items:
            $ref: '#/components/schemas/Tag'
        git:
          oneOf:
            - $ref: '#/components/schemas/GitBranch'
            - $ref: '#/components/schemas/GitCommit'
            - $ref: '#/components/schemas/GitTag'
        buildConfig:
          $ref: '#/components/schemas/buildConfig'
        templateInfo:
          $ref: '#/components/schemas/TemplateInfo'
        templateConfig:
          $ref: '#/components/schemas/TemplateConfig'
        manifest:
          $ref: '#/components/schemas/Manifest'
        status:
          $ref: '#/components/schemas/ClusterStatus'
        createdAt:
          type: string
          format: DateTime
        updatedAt:
          type: string
          format: DateTime
        createdBy:
          $ref: '#/components/schemas/User'
        updatedBy:
          $ref: '#/components/schemas/User'


    GetApplicationResponse:
      type: object
      properties:
        name:
          $ref: '#/components/schemas/Name'
        description:
          $ref: '#/components/schemas/Description'
        priority:
          $ref: '#/components/schemas/Priority'
        git:
          oneOf:
            - $ref: '#/components/schemas/GitBranch'
            - $ref: '#/components/schemas/GitCommit'
            - $ref: '#/components/schemas/GitTag'
        buildConfig:
          $ref: '#/components/schemas/buildConfig'
        templateInfo:
          $ref: '#/components/schemas/TemplateInfo'
        templateConfig:
          $ref: '#/components/schemas/TemplateConfig'
        manifest:
          $ref: '#/components/schemas/Manifest'
        fullPath:
          type: string
        groupID:
          $ref: "common.yaml#/components/schemas/GroupID"
        createdAt:
          type: string
          format: DateTime
        updatedAt:
          type: string
          format: DateTime

    Priority:
      type: string
      enum:
        - P0
        - P1
        - P2
        - P3

    buildConfig:
      type: object

    GitBranch:
      type: object
      properties:
        branch:
          type: string

    GitCommit:
      type: object
      properties:
        commit:
          type: string

    Scope:
      type: object
      properties:
        environment:
          type: string
        region:
          type: string
        regionDisplayName:
          type: string

    ClusterStatus:
      type: string
      enum:
        - ""
        - "Freeing"
        - "Freed"
        - "Deleting"
        - "Creating"

    GitTag:
      type: object
      properties:
        tag:
          type: string

    Manifest:
      type: object

    TemplateConfig:
      type: object

    TemplateInfo:
      type: object
      required:
        - type
      properties:
        type:
          type: string
          enum:
            - template
            - helm
        name:
          description: the template name
          type: string
        release:
          description: the release version of template
          type: string


    Name:
      type: string
      maxLength: 64
      description: the Name



    Description:
      type: string
      maxLength: 1024
      description: the group description

    Tag:
      type: object
      properties:
        key:
          type: string
        value:
          type: string

    User:
      type: object
      properties:
        id:
          $ref: "common.yaml#/components/schemas/ID"
        name:
          type: string
        email:
          type: string

