openapi: 3.0.1
info:
  title: Horizon-Environments-Restful
  version: 1.0.0
servers:
  - url: 'http://localhost:8080/'
paths:
  /apis/core/v1/environments:
    get:
      tags:
        - environment
      operationId: listEnvironments
      summary: list environments
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                example: |
                  {
                      "data":[
                          {
                              "name":"dev"
                          },
                          {
                              "name":"test"
                          },
                          {
                              "name":"reg"
                          },
                          {
                              "name":"perf"
                          },
                          {
                              "name":"pre"
                          },
                          {
                              "name":"beta"
                          },
                          {
                              "name":"online"
                          }
                      ]
                  }
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "common.yaml#/components/schemas/Error"

  /apis/core/v1/environments/{environment}/regions:
    get:
      tags:
        - environment
      operationId: listRegions
      summary: list regions of a environment
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                example: |
                  {
                      "data":[
                          {
                              "name": "yq"
                          },
                          {
                              "name": "dg"
                          },
                          {
                              "name": "eks"
                          }
                      ]
                  }
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "common.yaml#/components/schemas/Error"