openapi: 3.0.1
info:
  title: Horizon-Kubernetes-Restful
  version: 1.0.0
servers:
  - url: 'http://localhost:8080/'
paths:
  /apis/core/v1/kubernetes:
    get:
      tags:
        - kubernetes
      operationId: listKubernetes
      summary: list kubernetes
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                data:
                  type: array
                  items:
                    $ref: '#/components/schemas/Kubernetes'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "common.yaml#/components/schemas/Error"
    post:
      tags:
        - kubernetes
      operationId: createKubernetes
      summary: create a kubernetes
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Kubernetes"
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                data:
                  type: integer
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "common.yaml#/components/schemas/Error"

  /apis/core/v1/kubernetes/{kubernetesID}:
    parameters:
      - name: kubernetesID
        in: path
    get:
      tags:
        - kubernetes
      operationId: getKubernetes
      summary: get a kubernetes
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Kubernetes'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "common.yaml#/components/schemas/Error"
    put:
      tags:
        - kubernetes
      operationId: updateKubernetes
      summary: update a kubernetes
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Kubernetes'
      responses:
        '200':
          description: Success
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "common.yaml#/components/schemas/Error"
    delete:
      tags:
        - kubernetes
      operationId: deleteKubernetes
      summary: delete a kubernetes
      responses:
        '200':
          description: Success
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "common.yaml#/components/schemas/Error"

components:
  schemas:
    Kubernetes:
      type: object
      required:
        - id
        - name
        - displayName
        - server
        - certificate
        - ingressDomain
        - disabled
        - harborID
        - harbor
        - tags
        - tags
        - createdAt
        - updatedAt
      properties:
        id:
          type: integer
        name:
          type: string
        displayName:
          type: string
        server:
          type: string
        certificate:
          type: string
        ingressDomain:
          type: string
        disabled:
          type: boolean
        harborID:
          type: integer
        harbor:
          type: object
          properties:
            name:
              type: string
        tags:
          type: array
          items:
            type: object
            properties:
              key: string
              value: string
        createdAt:
          $ref: "common.yaml#/components/schemas/Date"
        updatedAt:
          $ref: "common.yaml#/components/schemas/Date"

