openapi: 3.0.3
info:
  title: Horion-APP
  description: the horizon-app restful api
  version: 1.0.0
servers:
  - url: 'http://localhost:8080'
paths:
  /apis/core/v1/groups/{groupID}/oauthapps:
    parameters:
      - name: groupID
        in: path
        description: groupid
        $ref:  "common.yaml#/components/schemas/GroupID"
        required: true
    post:
      tags:
        - oauthapp
      operationId: createoauthapp
      summary: create a oauth app
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateOauthAppRequest"
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AppBasicInfo"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "common.yaml#/components/schemas/Error"
    get:
      tags:
        - app
      operationId: listapp
      summary: list the horizon app under the group
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/AppBasicInfo"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "common.yaml#/components/schemas/Error"
  /apis/core/v1/oauthapps/{appID}:
    get:
      tags:
        - app
      summary: get a horizon app
      operationId: getapp
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AppBasicInfo"
        default:
          description:  Unexpected error
          content:
            application/json:
              schema:
                $ref: "common.yaml#/components/schemas/Error"
    delete:
      tags:
        - app
      summary: delete the horizon app
      operationId: deleteapp
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AppBasicInfo"
        default:
          description:  Unexpected error
          content:
            application/json:
              schema:
                $ref: "common.yaml#/components/schemas/Error"
    put:
      tags:
        - app
      summary: update the horizon app
      operationId: updateapp
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AppBasicInfo"
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AppBasicInfo"
        default:
          description:  Unexpected error
          content:
            application/json:
              schema:
                $ref: "common.yaml#/components/schemas/Error"


components:
  schemas:
    CreateOauthAppRequest:
      type: object
      properties:
        Name:
          $ref: '#/components/schemas/appName'
        Desc:
          $ref: "common.yaml#/components/schemas/Description"
        HomeURL:
          $ref: "common.yaml#/components/schemas/URL"
        RedirectURL:
          $ref: "common.yaml#/components/schemas/URL"

    AppBasicInfo:
      type: object
      properties:
        AppID:
          $ref: "common.yaml#/components/schemas/ID"
        AppName:
          $ref: '#/components/schemas/appName'
        Desc:
          $ref: "common.yaml#/components/schemas/Description"
        HomeURL:
          $ref: "common.yaml#/components/schemas/URL"
        ClientID:
          type: string
          format: uuid
        RedirectURL:
          $ref: "common.yaml#/components/schemas/URL"

    appName:
      type: string
      maxLength: 2048
      description: the group FullName
